- name: "4.1 Ensure that a user for the container has been created (Manual)"
  shell: |
    result=true
    docker ps --quiet | while read container; do
      uid=$(docker exec "$container" awk '/^Uid:/ {print $3}' /proc/1/status)
      if [[ "$uid" == "0" ]]; then
        echo "container $container is running as root"
        result=false
      fi
    done
    if [[ "$result" == "false" ]]; then exit 1; fi
  register: check_containers
  changed_when: false
  failed_when: check_containers.rc != 0
  tags:
    - scored
    - section4.1

- name: 4.2 Ensure that containers use only trusted base images (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.2

- name: 4.3 Ensure that unnecessary packages are not installed in the container (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.3

- name: 4.4 Ensure images are scanned and rebuilt to include security patches (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.4

- name: 4.5 Ensure Content trust for Docker is Enabled (Automated)
  lineinfile:
    path: /etc/environment
    line: DOCKER_CONTENT_TRUST=1
    state: present
  tags:
   - scored
   - section4.5

- name: 4.6 Ensure that HEALTHCHECK instructions have been added to container images (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - scored
   - section4.6

- name: 4.7 Ensure update instructions are not used alone in Dockerfiles (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.7

- name: 4.8 Ensure setuid and setgid permissions are removed (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.8

- name: 4.9 Ensure that COPY is used instead of ADD in Dockerfiles (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.9

- name: 4.10 Ensure secrets are not stored in Dockerfiles (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.10

- name: 4.11 Ensure only verified packages are installed (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.11

- name: 4.12 Ensure all signed artifacts are validated (Not Implemented)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section4.12
